project:
  type: book
  output-dir: docs

book:
  title: Documentation of the Process Rate Estimator R package PRE
  author: Damian Oswald
  date: 2024-01-12
  chapters:
    - index.qmd
    - introduction.qmd
    - data-preparation.qmd
    - running-the-model.qmd
    - results.qmd
    - references.qmd

bibliography: resources/references.bib
csl: resources/nature.csl

format:
  html:
    theme: default



