project:
  type: book
  output-dir: docs

book:
  title: Process Rate Estimator (`PRE`)
  chapters:
    - index.qmd
    - introduction.qmd
    - data-preparation.qmd
    - running-the-model.qmd
    - results.qmd
    - sensitivity-analysis.qmd
    - references.qmd
  reader-mode: true
  repo-url: https://github.com/damian-oswald/process-rate-estimator/
  repo-actions: [source, issue]
  navbar:
    title: Process Rate Estimator
    background: dark
    foreground: light
    search: true

bibliography: resources/references.bib
csl: resources/ecology.csl

format:
  html:
    theme: resources/theme.scss
    number-sections: true
    number-depth: 2
    reference-location: margin

mermaid: 
  theme: neutral
code-annotations: hover

