project:
  type: book
  output-dir: docs

book:
  title: Process Rate Estimator (`PRE`)
  chapters:
    - index.qmd
    - introduction.qmd
    - data-preparation.qmd
    - running-the-model.qmd
    - results.qmd
    - sensitivity-analysis.qmd
    - references.qmd

bibliography: resources/references.bib
csl: resources/ecology.csl

format:
  html:
    theme: default



