---
title: Process Rate Estimator
subtitle: A modeling side-hustle for the ETH group sustainable agroecosystems
author: Damian Oswald
date: 2023-09-23
date-format: long
number-sections: true
bibliography: references.bib
csl: nature.csl
notes-after-punctuation: true
format:
   gfm:
      output-file: README.md
      link-citations: true
      toc: false
   pdf:
      documentclass: article
      geometry: margin=2cm
      toc: true
      include-in-header:
         text: |
            \usepackage[version=4]{mhchem}
      link-citations: true
---

# Introduction

Denitrification is the natural process by which nitrate (NO~3~^-^) in the soil are converted by bacteria into nitrous oxide (N~2~O) or pure nitrigen (N~2~). The latter is called *total denitrification* --- the full process described in @eq-denitrification takes place.

$$
\ce{NO3^- ->[\text{Nitrate}][\text{reductase}] NO2^- ->[\text{Nitrite}][\text{reductase}] NO ->[\text{Nitrite oxide}][\text{reductase}] N2O^- ->[\text{Nitrous oxide}][\text{reductase}] N2}
$${#eq-denitrification}

Denitrification occurs in conditions where oxygen is limited, such as waterlogged soils. It is part of the nitrogen cycle, where nitrogen is circulated between the atmosphere, organisms and the earth.

# Formal model description

The diffusion fluxes between soil increments are described by Frick's law (@eq-frick).

$$F_{\text{calc}} = \frac{dC}{dZ} D_{\text s} \rho$${#eq-frick}

Here, $D_s$ is the gas diffusion coefficient, $\rho$ is the gas density of N~2~O, and $\frac{dC}{dZ}$ is the N~2~O concentration gradient from lower to upper depth.
The fluxes are calculated based on N~2~O concentration gradients between 105-135 cm, 75-105 cm, 45-75 cm, 15-45 cm, and 0-15 cm depth layers, and ambient air above the soil surface.

$\theta_w$ is the soil volumetric water content, $\theta_a$ the air-filled porosity, and $\theta_T$ is the total soil porosity.

The gas diffusion coefficient $D_{\text s}$ was calculated according @eq-Ds as established by Millington and Quirk in 1961 [@millington1961permeability].

$$D_{\text s} = \left( \frac{\theta_w^{\frac{10}{3}} + D_{\text fw}}{H} + \theta_a^{\frac{10}{3}} \times D_{\text fa} \right) \times \theta_T^{-2}$${#eq-Ds}

Here, $H$ represents a dimensionless form of Henry's solubility constant ($H'$) for N~2~O in water at a given temperature. The constant $H$ for N~2~O is calculated as follows:

$$H = \frac{8.5470 \times 10^5 \times \exp \frac{-2284}{\text T}}{\text R \times \text T}$${#eq-H}

Here, $\text R$ is the gas constant, and $\text T$ is the temperature ($\text T = 298 \; \text K$).

$D_{\text{fw}}$ was calculated according to @eq-Dfw as documented by Versteeg and Van Swaaij (1988) [@versteeg1988solubility].

$$D_{\text{fw}} = 5.07 \times 10^{-6} \times \exp \frac{-2371}{\text T}$${#eq-Dfw}

$$D_{\text{fa}} = D_{\text{fa, NTP}} \times \left( \frac{\text T}{273.15} \right)^n \times \left( \frac{101'325}{\text P} \right)$${#eq-Dfa}


# The data

The study uses data collected from a mesocosm experiment -- i.e. an outdoor experiment that examines the natural environment under controlled conditions. The experiment was set up as a randomized complete block design, with 4 varieties and 3 replicates, using 12 non-weighted lysimeters. A non-weighted lysimeter is a device to measure the amount of water that drains through soil, and to determine the types and amounts of dissolved nutrients or contaminants in the water. Each lysimeter had five sampling ports with soil moisture probes and custom-built pore gas sample, at depths of 7.5, 30, 60, 90 and 120 cm below soil surface.

$$4 \times 3 \times 5 \times 161 = 9660$${#eq-dimension}

@eq-dimension shows how many observations we should expect to have. In reality, some observations are missing.

# Model parameters

| Symbol           | Code          | Name                                      | Value                 | Unit |            |
|:-----------------|:--------------|:------------------------------------------|:----------------------|:-----|-----------:|
| $BD$             | `BD`          | Bulk density                              | $1.686$               |      |            |
| $\theta_w$       | `theta_w`     | Soil volumetric water content             |                       |      |            |
| $\theta_a$       | `theta_a`     | Air-filled porosity                       |                       |      |            |
| $\theta_\text T$ | `theta_T`     | Total soil porosity                       | $1-\frac{BD}{2.65}$   |      |            |
| $\text T$        | `temperature` | Soil temperature                          | $298$                 | K    |            |
| $D_{\text{fw}}$  | `D_fw`        | Diffusivity of N~2~O in water             | [see eq. @eq-Dfw]     |      | [-@eq-Dfw] |
| $D_{\text{fa}}$  | `D_fa`        | Diffusivity of N~2~O in air               |                       |      | [-@eq-Dfa] |
| $H$              | `H`           | Dimensionless Henry's solubility constant |                       |      | [-@eq-H]   |
| $\rho$           | `rho`         | Gas density of N~2~O                      | $1.26 \times 10^6$    |      |            |

: Overview of the parameters used in the model. {#tbl-parameters tbl-colwidths="[10,20,50,20,20,10]"}

# References {-}



