---
title: Questions regarding the process rate estimator project
author: Damian Oswald
---

# Questions Round I

- In the data set, some dates are missing. I think that the missing date could be 2016-02-03, i.e. the last day, but maybe I'm mistaken. There are 40 observations with missing dates, and they seemingly all refer to the same date; as all observations from row 5-12 are missing this specific date. (That would be all the columns with 161 days of observations instead of 160...)
- Regarding that: Why do we have 160 measurements for column 1:4 and 161 for column 5:12?
- Some moisture observations are missing, specifically from column 6 at depth = 90 cm. Why are there these missing observations? (Did maybe some sensor break?)
- Also, is it correct that the flux data was only measured on specific days? These dates seem somewhat irregular -- how were they chosen?
- In the model code, why is only the column C1 selected for the processing?
- Do you have some explanation of the variables in the data set? For some variable, I have trouble to deduct what they mean.
- For example: What is `CN`? Why does it have `Inf` values? (I guess its a ratio, maybe C:N ratio, and some values were divided by zero?)
- What is the variable `increment`? Is increment the same as `depth < 15`?
- Here's a table of the number of observations (with present flux data) per date and column. Why are they so inconsistent? (Because the description mentions to a complete block design, but maybe that only refers to the spatial design?)

            column
date         1 2 3 4 5 6 7 8 9 10 11 12
  2015-09-02 5 5 5 5 5 5 5 5 5  5  5  5
  2015-09-08 3 3 3 5 4 5 5 5 5  5  4  5
  2015-09-16 3 3 2 0 0 0 3 2 0  0  0  1
  2015-09-23 2 2 0 1 3 4 5 5 4  3  5  4
  2015-09-30 3 3 0 5 4 2 4 4 5  5  5  5
  2015-10-07 5 5 5 5 4 4 4 5 5  5  5  5
  2015-10-14 5 5 5 5 5 4 5 5 5  5  5  5
  2015-10-18 0 0 0 0 0 0 0 0 0  0  0  1
  2015-10-21 5 5 5 5 5 4 5 5 5  4  5  5
  2015-10-28 4 4 5 5 5 4 5 5 5  5  4  4
  2015-11-04 5 5 4 4 3 4 5 5 5  5  5  5
  2015-11-11 2 5 5 5 4 3 4 5 5  5  5  5
  2015-11-18 4 5 5 5 5 4 5 5 5  5  5  5
  2015-11-25 4 3 1 3 5 4 5 5 5  5  5  5
  2015-12-02 5 5 5 5 5 4 5 5 5  5  5  5
  2015-12-09 5 5 5 5 5 5 5 5 5  5  5  5
  2015-12-16 5 5 5 5 1 4 5 5 5  4  5  5
  2015-12-22 5 5 5 5 5 5 5 5 5  5  5  5
  2015-12-29 5 5 5 5 5 2 0 0 2  3  5  5
  2016-01-05 0 0 0 0 0 0 0 0 2  0  2  2
  2016-01-06 5 5 5 5 5 5 5 4 3  5  3  3
  2016-01-12 5 5 5 4 5 5 5 5 5  4  5  4
  2016-01-19 5 5 5 5 5 5 5 5 5  5  5  4
  2016-01-26 2 2 2 1 2 2 1 0 0  0  0  0
  
- I am asking these questions because I was thinking of transforming the data to a complete data cube (a 4-d array probably), but then I need to know exactly how the data came to be, and what's up with the missing observations. (Some values are `NA`, but then, also some Rows / Depths are completely missing for some days.)
- When calculating dC/dZ, you essentially calculate the following:

      ```r
      # calculate dC/dz across depths
      data_C1$dCdz_top_7 <- (data_C1$corrected.N2O_7 - N2Oatm)/1000000/(15/100/2)
      data_C1$dCdz_top_30 <- (data_C1$corrected.N2O_30 - data_C1$corrected.N2O_7)/1000000/(30/100/2+15/100/2)
      data_C1$dCdz_top_60 <- (data_C1$corrected.N2O_60 - data_C1$corrected.N2O_30)/1000000/(30/100/2+30/100/2)
      data_C1$dCdz_top_90 <- (data_C1$corrected.N2O_90 - data_C1$corrected.N2O_60)/1000000/(30/100/2+30/100/2)
      data_C1$dCdz_top_120 <- (data_C1$corrected.N2O_120 - data_C1$corrected.N2O_90)/1000000/(30/100/2+30/100/2)
      ```
      
      I do not understand the last terms in each calculations. Why do you calculate `(30/100/2+30/100/2)` three times, but then `(30/100/2+15/100/2)` once? (I can't find the corresponding formula -- what do these numbers correspond to?)

# Questions Round II

- How should we do the hypertuning of the bandwidth? All variables the same; one per variable, one per variable and depth, one per variable and depth and column.

