# Sensitivity Analysis

Sensitivity analysis is a method used to determine how different values of an independent variable impact a particular dependent variable under a given set of assumptions. This technique is used in various fields such as finance, engineering, and environmental studies to test the robustness of models against changes in input values. By systematically varying key parameters, sensitivity analysis helps in identifying which variables have the most significant impact on the outcome, aiding in decision-making and risk assessment.

:::{.column-page}

| End Member             |                                 | Value [‰] | Value reference         | Sampling                         | Range reference   |
|------------------------|---------------------------------|-----------|-------------------------|----------------------------------|-------------------|
| `eta_SP_diffusion`     | $\eta\: \text{SP}_\text{diff.}$ | 1.55      | @well2008isotope        | $\sim \mathcal{N}(1.55, 0.28^2)$ | @well2008isotope  |
| `eta_18O_diffusion`    | $\eta\ce{^{18}O}_\text{diff.}$  | -7.79     | @well2008isotope        | $\sim \mathcal{N}(-7.79, 0.27^2)$| @well2008isotope  |
| `SP_nitrification`     | $\text{SP}_\text{nit.}$         | 34.4      | @decock2013potential    | $\sim \mathcal{U}(26.2, 34.6)$   | @denk2017nitrogen |
| `d18O_nitrification`   | $\delta\ce{^{18}O_\text{nit.}}$ | 36.5      | @lewicka2017quantifying | $\sim \mathcal{N}(36.5, 2^2)$    |                   |
| `SP_denitrification`   | $\text{SP}_\text{den.}$         | -2.4      | @decock2013potential    | $\sim \mathcal{U}(-2.4, -0.9)$   | @denk2017nitrogen |
| `d18O_denitrification` | $\delta\ce{^{18}O_\text{den.}}$ | 11.1      | @lewicka2017quantifying | $\sim \mathcal{N}(11.1, 2^2)$    |                   |
| `eta_SP_reduction`     | $\eta\:\text{SP}_\text{red.}$   | -5.3      | @denk2017nitrogen       | $\sim \mathcal{U}(-8, -2)$       | @denk2017nitrogen |
| `eta_18O_reduction`    | $\eta\ce{^{18}O_\text{red.}}$   | -16.1     | @lewicka2017quantifying |                                  |                   |

: Isotope end members values used for modeling gross nitrification derived N~2~O production, gross denitrification derived N~2~O production, and gross N~2~O reduction. @lewicka2017quantifying originally report $\delta \ce{^{18} O \text - N2O} (\ce{N2O}/\ce{H2O})$. When a range is indicated, a random number from the range was selected in each iteration. When an average and standard deviation is indicated, a random value was drawn from the normal distribution in each iteration. {#tbl-sensitivity tbl-colwidths="[15,10,10,20,15,20]"}

:::